### ISSUE TITLE
can you upload a csv example, have no idea to create a correct csv

### ISSUE THREAD

**Issue by baidang201** [paritytech/uniques-campaign-runner#2]

**Comment by hamidra** [comment]
I added some sample csv  and workflow files in the example folder.

- for minting some simple NFTs with no customization per NFT you just need a row per NFT in your csv file. e.x. "NFT #"  check the simple example:
https://github.com/hamidra/uniques-campaign-runner/tree/main/example/simple

- For minting scenarios which need to customize the NFTs using data from your csv, you can use the data from the csv columns in the workflow by using this interpolation format <<csv column name>> check the advanced example:
https://github.com/hamidra/uniques-campaign-runner/tree/main/example/advanced

**Comment by baidang201** [comment]
thanks
